export enum authConstants {
  REGISTRATION_REQUEST = "REGISTRATION_REQUEST",
  REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS",
  REGISTRATION_FAILURE = "REGISTRATION_FAILURE",

  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE",

  LOGOUT_REQUEST = "LOGOUT_REQUEST",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
  LOGOUT_FAILURE = "LOGOUT_FAILURE",

  VERIFY_TOKEN_REQUEST = "VERIFY_TOKEN_REQUEST",
  VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS",
  VERIFY_TOKEN_FAILURE = "VERIFY_TOKEN_FAILURE",
}

export enum LoanDetailsConstants {
  SAVE_LOAN_DETAILS_REQUEST = "SAVE_LOAN_DETAILS_REQUEST",
  SAVE_LOAN_DETAILS_SUCCESS = "SAVE_LOAN_DETAILS_SUCCESS",
  SAVE_LOAN_DETAILS_FAILURE = "SAVE_LOAN_DETAILS_FAILURE",
}
