export enum authConstants {
  REGISTRATION_REQUEST = "REGISTRATION_REQUEST",
  REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS",
  REGISTRATION_FAILURE = "REGISTRATION_FAILURE",

  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE",

  LOGOUT_REQUEST = "LOGOUT_REQUEST",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
  LOGOUT_FAILURE = "LOGOUT_FAILURE",

  VERIFY_TOKEN_REQUEST = "VERIFY_TOKEN_REQUEST",
  VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS",
  VERIFY_TOKEN_FAILURE = "VERIFY_TOKEN_FAILURE",
}

export enum LoanDetailsConstants {
  SAVE_LOAN_DETAILS_REQUEST = "SAVE_LOAN_DETAILS_REQUEST",
  SAVE_LOAN_DETAILS_SUCCESS = "SAVE_LOAN_DETAILS_SUCCESS",
  SAVE_LOAN_DETAILS_FAILURE = "SAVE_LOAN_DETAILS_FAILURE",

  GET_LOAN_DETAILS_REQUEST = "GET_LOAN_DETAILS_REQUEST",
  GET_LOAN_DETAILS_SUCCESS = "GET_LOAN_DETAILS_SUCCESS",
  GET_LOAN_DETAILS_FAILURE = "GET_LOAN_DETAILS_FAILURE",
}

export enum PersonalDetailsConstants {
  SAVE_PERSONAL_DETAILS_REQUEST = "SAVE_PERSONAL_DETAILS_REQUEST",
  SAVE_PERSONAL_DETAILS_SUCCESS = "SAVE_PERSONAL_DETAILS_SUCCESS",
  SAVE_PERSONAL_DETAILS_FAILURE = "SAVE_PERSONAL_DETAILS_FAILURE",

  GET_PERSONAL_DETAILS_REQUEST = "GET_PERSONAL_DETAILS_REQUEST",
  GET_PERSONAL_DETAILS_SUCCESS = "GET_PERSONAL_DETAILS_SUCCESS",
  GET_PERSONAL_DETAILS_FAILURE = "GET_PERSONAL_DETAILS_FAILURE",
}

export enum IncomeDetailsConstants {
  SAVE_INCOME_DETAILS_REQUEST = "SAVE_INCOME_DETAILS_REQUEST",
  SAVE_INCOME_DETAILS_SUCCESS = "SAVE_INCOME_DETAILS_SUCCESS",
  SAVE_INCOME_DETAILS_FAILURE = "SAVE_INCOME_DETAILS_FAILURE",

  GET_INCOME_DETAILS_REQUEST = "GET_INCOME_DETAILS_REQUEST",
  GET_INCOME_DETAILS_SUCCESS = "GET_INCOME_DETAILS_SUCCESS",
  GET_INCOME_DETAILS_FAILURE = "GET_INCOME_DETAILS_FAILURE",
}

export enum ExpenditureDetailsConstants {
  SAVE_EXPENDITURE_DETAILS_REQUEST = "SAVE_EXPENDITURE_DETAILS_REQUEST",
  SAVE_EXPENDITURE_DETAILS_SUCCESS = "SAVE_EXPENDITURE_DETAILS_SUCCESS",
  SAVE_EXPENDITURE_DETAILS_FAILURE = "SAVE_EXPENDITURE_DETAILS_FAILURE",

  GET_EXPENDITURE_DETAILS_REQUEST = "GET_EXPENDITURE_DETAILS_REQUEST",
  GET_EXPENDITURE_DETAILS_SUCCESS = "GET_EXPENDITURE_DETAILS_SUCCESS",
  GET_EXPENDITURE_DETAILS_FAILURE = "GET_EXPENDITURE_DETAILS_FAILURE",
}

export enum GetDecisionConstants {
  SAVE_DECISION_REQUEST = "SAVE_DECISION_REQUEST",
  SAVE_DECISION_SUCCESS = "SAVE_DECISION_SUCCESS",
  SAVE_DECISION_FAILURE = "SAVE_DECISION_FAILURE",

  GET_DECISION_REQUEST = "GET_DECISION_REQUEST",
  GET_DECISION_SUCCESS = "GET_DECISION_SUCCESS",
  GET_DECISION_FAILURE = "GET_DECISION_FAILURE",
}
